create schema if not exists stt_poc;

create table if not exists stt_poc.call_sessions (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'recording'
    check (status in ('recording', 'completed', 'failed')),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  caller_label text,
  created_at timestamptz not null default now()
);

create table if not exists stt_poc.transcript_chunks (
  id bigint generated by default as identity primary key,
  session_id uuid not null
    references stt_poc.call_sessions(id)
    on delete cascade,
  chunk_index integer not null,
  transcript text,
  audio_format text,
  duration_ms integer,
  created_at timestamptz not null default now(),
  unique (session_id, chunk_index)
);

create table if not exists stt_poc.drafts (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null
    references stt_poc.call_sessions(id)
    on delete cascade,
  draft_type text not null default 'summary',
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists transcript_chunks_session_id_idx
  on stt_poc.transcript_chunks(session_id);

create index if not exists drafts_session_id_idx
  on stt_poc.drafts(session_id);

revoke all on schema stt_poc from anon, authenticated;
revoke all on all tables in schema stt_poc from anon, authenticated;

grant usage on schema stt_poc to service_role;
grant all privileges on all tables in schema stt_poc to service_role;
grant all privileges on all sequences in schema stt_poc to service_role;